Fix build errors due to missing include
The errors occured after updating fmt from v5 to v6.

Errors were:

| GUIDialogProfileSettings.cpp: In static member function ‘static bool CGUIDialogProfileSettings::ShowForProfile(unsigned int, bool)’:
| GUIDialogProfileSettings.cpp:174:5: error: ‘assert’ was not declared in this scope
|      assert(profile);
|      ^~~~~~

| GraphicContext.cpp: In member function ‘void CGraphicContext::RestoreStereoFactor()’:
| GraphicContext.cpp:823:3: error: ‘assert’ was not declared in this scope
|    assert(m_stereoFactors.size());
|    ^~~~~~