[PR 24552] [swig] Fix building with Swig 4.2.0
swig 4.2.0 introduced a change that adds a constructor to the generated AddonModuleXbmcaddon.i.cpp
file. This causes failures such as

build/swig/AddonModuleXbmcaddon.i.cpp: In function 'PyObject* PythonBindings::xbmcaddon_XBMCAddon_xbmcaddon_Settings_New(PyTypeObject*, PyObject*, PyObject*)':
build/swig/AddonModuleXbmcaddon.i.cpp:1751:52: error: no matching function for call to 'XBMCAddon::xbmcaddon::Settings::Settings()'
 1751 |     apiResult = new XBMCAddon::xbmcaddon::Settings();
      |                                                    ^
In file included from ../xbmc/interfaces/legacy/Addon.h:14,
                 from build/swig/AddonModuleXbmcaddon.i.cpp:30:
../xbmc/interfaces/legacy/Settings.h:58:3: note: candidate: 'XBMCAddon::xbmcaddon::Settings::Settings(std::shared_ptr<CSettingsBase>)'
   58 |   Settings(std::shared_ptr<CSettingsBase> settings);
      |   ^~~~~~~~
../xbmc/interfaces/legacy/Settings.h:58:3: note:   candidate expects 1 argument, 0 provided

If we disable the contructor for Settings, we get the same generated output as swig <=4.1.1